module.exports = {
    url: 'http://142.151.168.178:8067',
    options: [
        'has a driver licsense outside of Ontario',
        'released an app before',
        'has a GitHub account',
        'takes the Go bus to school',
        'has never watched Game of Thrones or Breaking Bad',
        'is a Whovian (Dr. Who fanatic)',
        'who has read a Hunger Games book',
        'has taken some form of martial arts',
        'plays an instrument',
        'has never coded before',
        'does not have a Facebook account',
        'has their own website',
        'has travelled to 4 continents',
        'has never owned an Apple product',
        'is wearing UofT apparel',
        'can speak 3 or more languages',
        'has a birthday in the same month as you',
        'is in 4th year',
        'is not in CS or ENG',
        'has the same hobby as you',
        'is in the same program and year as you',
        'has 2 or more pets',
        'is wearing a denim shirt',
        'is the youngest in the family',
        'is a member of UofTDev since last year',
        'is on an internship or working',
        'has been to a concert the past month',
        'has contributed to an Open Source project',
        'has Tinder on their phone installed now',
        'has scored more than 100 on Flappy Bird',
        'has beaten 2048'
    ]
};
